name: Frontend CI (React + TS)

on:
  push:
    branches: [ "main", "dev", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          

      - name: Install Dependencies
        working-directory: ./project
        run: npm install

      - name: TypeScript Check
        working-directory: ./project
        run: npx tsc --noEmit

      - name: Build Project
        working-directory: ./project
        run: npm run build